const Constantes = {
  FormatDate: {
    DATE: 'yyyy-MM-dd',
    DATE_TIME: 'yyyy-MM-dd HH:mm:ss',
    MONTH_DES: 'MMMM'
  },
  ROUTES: {
    _LOGIN: 'login',
    _HOME: 'home',
    _USERS: 'users',
    _APP: 'app',
    _ADMIN: 'app',
    APP: {
      BK: 'app-backus',
      PERNORP: 'app-pernod',
    },
    REPORTS: {
      _EXHIBITION: 'exhibition',
      _PRICE: 'price',
      _FRENTE: 'frente',
      _INCIDENCE: 'incidence',
      _STOCK: 'stock',
      _SKU: 'sku',
      _POC: 'poc',
      _ESTRUCTURA_COMERCIAL: 'estructura-comercial',
      _EXHIBITION_DASHBOARD: 'exhibiciones-dashboard',
      _EXHIBITION_COMPETENCIA_DASHBOARD: 'exhibiciones-competencia-dashboard',
      _PRECIO_DASHBOARD: 'precio-dashboard',
      _FRENTE_DASHBOARD: 'frente-dashboard',
      _STOCK_DASHBOARD: 'stock-dashboard',
      _CONFIG_VALUE: 'config-value',
      _POCS_RELEVADOS: 'pocs-relevos',
      _BACKUP: 'backup',
    },
    UPLOAD:{
      // _ADICIONALES: 'upload-adicionales',
      _CONTRAPRESTADA: 'upload-contraprestada',
    },
    BK_HOME: 'home',
    _CLIENTE_BK: 'cliente',
    _ENCUESTA: 'encuesta',
    ENCUESTA: {
      //url short
      _PRECIO: 'precio',
      _EXHIBICIONES: 'exhibiciones',
      _FRENTES: 'frentes',
      _INCIDENCIA: 'incidencias',
      _STOCK: 'stock',
      PRECIO_GUARDAR: 'guardar-encuesta-precio',
      PRECIO_DETALLE: 'precio/detalle',
      EXHIBICIONES_CONTRAPRESTADAS: 'exhibiciones/contraprestadas',
      EXHIBICIONES_ADICIONALES: 'exhibiciones/adicionales',
      EXHIBICIONES_COMPETENCIA: 'exhibiciones/competencia',
      INCIDENCIA_COMPETENCIA: 'incidencias/competencia',
      INCIDENCIA_MUEBLES: 'incidencias/muebles',
      INCIDENCIA_NUEVO: 'incidencias/nuevo',
      INCIDENCIA_NUEVO_RECOJO: 'incidencias/nuevo/recojo',
      INCIDENCIA_NUEVO_MANTENIMIENTO: 'incidencias/nuevo/mantenimiento',
      INCIDENCIA_NUEVO_ASIGNACION: 'incidencias/nuevo/asignacion',
      //url large
      PRECIO: {
        DETALLE: 'detalle',
      },
      EXHIBICIONES: {
        CONTRAPRESTADAS: 'contraprestadas',
        ADICIONALES: 'adicionales',
        COMPETENCIA: 'competencia',
      },
      INCIDENCIA: {
        COMPETENCIA: 'competencia',
        MUEBLES: 'muebles',
        NUEVO: 'nuevo',
        RECOJO: 'recojo',
        MANTENIMIENTO: 'mantenimiento',
        ASIGNACION: 'asignacion',
      },
    },
  },
  CONFIG_VALUES:{
    MECANICA_PROMOCIONAL: 'mecanica_promocional',
    TIPO_ZONAS: 'tipo_zonas',
    TIPO_EXHIBICIONES: 'tipo_exhibiciones',
    TIPO_MUEBLE: 'tipo_mueble',
    TIPO_MUEBLE_RECOJO: 'tipo_mueble_recojo',
    MOTIVO_RECOJO: 'motivo_recojo',
    TIPO_MANTENIMIENTO: 'tipo_mantenimiento',
    TIPO_INCIDENCIA_COMPETENCIA: 'tipo_incidencia_competencia',
    SKU_LINEA_MARCA: 'sku_linea_marca',
    SKU_LINEA_CATEGORIAS: "sku_linea_categorias",
    TIPO_EXHIBICION_HOMOLOGADO_CONTRAPRESTADA: 'tipo_exhibicion_homologado_contraprestada'
  },
  TIPO_EMPRESA: {
    COMPETENCIA: 1,
    NO_COMPENTENCIA: 0,
  },
  MONTHS: [
    {label: 'Enero', value: '01', checked: false},
    {label: 'Febrero', value: '02', checked: false},
    {label: 'Marzo', value: '03', checked: false},
    {label: 'Abril', value: '04', checked: false},
    {label: 'Mayo', value: '05', checked: false},
    {label: 'Junio', value: '06', checked: false},
    {label: 'Julio', value: '07', checked: false},
    {label: 'Agosto', value: '08', checked: false},
    {label: 'Septiembre', value: '09', checked: false},
    {label: 'Octubre', value: '10', checked: false},
    {label: 'Noviembre', value: '11', checked: false},
    {label: 'Diciembre', value: '12', checked: false}
  ],
  COLORS: [
    '#F7DC1F',
    '#E9D069',
    '#C7CA66',
    '#D2691E',
    '#DCAE2E',
    '#E2BBC9',
    '#FF8C00',
    '#BC8F8F',
    '#FFDFB1',
    '#E4D86F',
    '#F2E715',
    '#F5C559',
    '#E7E088',
    '#F9D056', // PALETA
    '#EDF6B0',
    '#C7CA66',
    '#FFFFEB',
    '#F1E099',
    '#FDD02D',
    '#c9bb50',
    '#D4D570',
    '#F0E58B',
    '#DAA520',
    '#FFE4B4',
    '#FFF8DC',
    '#FFDEAD',
    '#FADC9B',
    '#DEB786',
    '#CD853F',
    '#A0522C',
    '#CD5C5B',
    '#EBEC86',
    '#DCFFFE',
    '#DCFFFE',
    '#EBD45E',
    '#DFDF7B',
    '#F6F791',
  ]
};

export default Constantes;
