export const environment = {
  // backendUrl: 'https://backus-kkaa-merch-backend-dev.azurewebsites.net',
  backendUrl: 'http://localhost:3000',
  secret_key: '2024',
  bd_index_merch: 'backus-kkaa-merch',
  tb_index_imagen: 'imagen',
  tb_index_exhibicion_adicional: 'exhibicion_adicional',
  tb_index_exhibicion_competencia: 'exhibicion_competencia',
  tb_index_exhibicion_contraprestada: 'exhibicion_contraprestada',
  tb_index_exhibicion_adicional_renovable: 'exhibicion_adicional_renovable',
  tb_index_exhibicion_competencia_renovable: 'exhibicion_competencia_renovable',
  tb_index_users: 'users',
  tb_index_poc: 'poc',
  tb_index_sku: 'sku',
  tb_index_config_value: 'config_value',
  tb_index_frente: 'frente',
  tb_index_stock: 'stock',
  tb_index_precio: 'precio',
  tb_index_incidencia_competencia: 'incidencia_competencia',
  tb_index_incidencia_mueble_asignacion: 'incidencia_mueble_asignacion',
  tb_index_incidencia_mueble_mantenimiento: 'incidencia_mueble_mantenimiento',
  tb_index_incidencia_mueble_recojo: 'incidencia_mueble_recojo',
};
